version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Se o Dockerfile estiver no diretório raiz
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["sh", "-c", "composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan migrate && php artisan test && php-fpm"]
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
